### ISSUE TITLE
'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'

### ISSUE THREAD

**Issue by krystofbe** [shivero/webpack-4-react-bootstrap-starter-template#2]
Is `postcss-cssnext` even used here? Can't find it in the webpack conf

**Comment by shivero** [comment]
Hello,
Currently, `postcss-cssnext` is only included as devDependency ready for configuration.
I've started rewriting `webpack.config.js` - main reason: `extract-text-webpack-plugin`  (https://github.com/webpack-contrib/extract-text-webpack-plugin) has been DEPRECATED in favor of `mini-css-extract-plugin` (https://github.com/webpack-contrib/mini-css-extract-plugin).

Migration is almost completed and will be pushed - stay tuned
